services:
  postgres:
    image: postgres:latest
    container_name: hotel_postgres
    restart: always
    environment: #replace with .env values ;nah, its just local...
      POSTGRES_USER: user
      POSTGRES_PASSWORD: pass
      POSTGRES_DB: hotel_db
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

volumes:
  postgres-data:
