spring:
  datasource:
    url: jdbc:h2:mem:devDB
    driver-class-name: org.h2.Driver
    username: devUser
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    root: info
    gr.balasis.hotel.core: trace
customMessage: "Development environment is up..."