spring:
  datasource:
    url: jdbc:h2:mem:devDB #sample to be changed...
    driver-class-name: org.h2.Driver
    username: prodUsername
  jpa:
    hibernate:
      ddl-auto: update
logging:
  level:
    root: info
    gr.balasis.hotel.core: trace
    gr.balasis.hotel.modules.feedback: trace
customMessage: "Development environment is up including restaurant module"