spring:
  datasource:
    url: jdbc:h2:mem:testingDB
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: create
logging:
  level:
    root: info
    gr.balasis.hotel.core.service: trace