spring:
  profiles:
    active: @spring.profile.from.maven@

server:
  port: 3000


logging:
  level:
    root: info
    gr.balasis.hotel.engine.core: trace
    gr.balasis.hotel.engine.monitoring: trace

